version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 7000 -b '0.0.0.0'"
    ports:
      - "7000:7000"
    links:
      - db:postgres
